<?php

namespace App\Services\Assets;

if(!defined('MAX_IMAGES_SIZE')) define('MAX_IMAGES_SIZE', 2000);

/**
 * BANNER DIMENSION
 */
if(!defined('HOME_BANNER_IMAGE_WIDTH')) define('HOME_BANNER_IMAGE_WIDTH', 1620);
if(!defined('HOME_BANNER_IMAGE_HEIGHT')) define('HOME_BANNER_IMAGE_HEIGHT', 1080);

/**
 * NEWS DIMENSION
 */
if(!defined('HOME_THUMBNAIL_NEWS_IMAGE_WIDTH')) define('HOME_THUMBNAIL_NEWS_IMAGE_WIDTH', 412);
if(!defined('HOME_THUMBNAIL_NEWS_IMAGE_HEIGHT')) define('HOME_THUMBNAIL_NEWS_IMAGE_HEIGHT', 293);

if(!defined('THUMBNAIL_NEWS_IMAGE_WIDTH')) define('THUMBNAIL_NEWS_IMAGE_WIDTH', 376);
if(!defined('THUMBNAIL_NEWS_IMAGE_HEIGHT')) define('THUMBNAIL_NEWS_IMAGE_HEIGHT', 573);

if(!defined('NEWS_DETAIL_IMAGE_WIDTH')) define('NEWS_DETAIL_IMAGE_WIDTH', 1044);
if(!defined('NEWS_DETAIL_IMAGE_HEIGHT')) define('NEWS_DETAIL_IMAGE_HEIGHT', 693);

/**
 * VIDEO DIMENSION
 */
if(!defined('HOME_THUMBNAIL_VIDEO_IMAGE_WIDTH')) define('HOME_THUMBNAIL_VIDEO_IMAGE_WIDTH', 403);
if(!defined('HOME_THUMBNAIL_VIDEO_IMAGE_HEIGHT')) define('HOME_THUMBNAIL_VIDEO_IMAGE_HEIGHT', 285);

if(!defined('THUMBNAIL_VIDEO_IMAGE_WIDTH')) define('THUMBNAIL_VIDEO_IMAGE_WIDTH', 293);
if(!defined('THUMBNAIL_VIDEO_IMAGE_HEIGHT')) define('THUMBNAIL_VIDEO_IMAGE_HEIGHT', 441);

if(!defined('DOCTOR_IMAGE_WIDTH')) define('DOCTOR_IMAGE_WIDTH', 201);
if(!defined('DOCTOR_IMAGE_HEIGHT')) define('DOCTOR_IMAGE_HEIGHT', 217);